'use client';
import React, { createContext, useContext, useState, ReactNode } from 'react';

type Lang = 'en' | 'ru';

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  en: {
    'nav.portfolio': 'Portfolio',
    'nav.news': 'News',
    'nav.articles': 'Articles',
    'nav.shop': 'Shop',
    'nav.forum': 'Forum',
    'nav.contact': 'Contact',
    'nav.login': 'Sign In',
    'hero.label': 'Creative Portfolio',
    'hero.title1': 'Where Craft',
    'hero.title2': 'Meets',
    'hero.title3': 'Intelligence',
    'hero.sub': '3D bas relief, medals & coins alongside AI-generated images and video — one creative universe.',
    'hero.cta1': 'Explore Portfolio',
    'hero.cta2': 'Visit Shop',
    'portfolio.label': 'Selected Works',
    'portfolio.title': 'Dual Creative Practice',
    'portfolio.sub': 'Handcrafted 3D models and AI-driven content, each discipline informing the other.',
    'portfolio.tab3d': '3D Modeling',
    'portfolio.tabAI': 'AI Content',
    'portfolio.viewAll': 'View Full Portfolio',
    'featured.label': 'Recent Highlights',
    'featured.title': 'Latest Creations',
    'news.label': 'Updates',
    'news.title': 'News & Articles',
    'news.sub': 'Insights on 3D modeling techniques, AI content generation, and the intersection of both.',
    'news.readMore': 'Read Article',
    'news.viewAll': 'All Articles',
    'shop.label': 'Shop',
    'shop.title': 'Own a Piece',
    'shop.sub': 'Digital downloads, 3D model files, and exclusive prints available for purchase.',
    'shop.addCart': 'Add to Cart',
    'shop.viewAll': 'Browse Shop',
    'forum.label': 'Community',
    'forum.title': 'Join the Discussion',
    'forum.sub': 'Connect with fellow 3D artists and AI enthusiasts. Share work, get feedback, discuss techniques.',
    'forum.join': 'Join Forum',
    'contact.label': 'Get in Touch',
    'contact.title': 'Commission or Collaborate',
    'contact.sub': 'Available for custom 3D modeling commissions, AI content projects, and creative collaborations.',
    'contact.send': 'Send Message',
    'contact.name': 'Your Name',
    'contact.email': 'Email Address',
    'contact.subject': 'Subject',
    'contact.message': 'Tell me about your project...',
    'footer.tagline': 'Where 3D craft meets AI intelligence.',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Create Account',
    'auth.email': 'Email address',
    'auth.password': 'Password',
    'auth.name': 'Full name',
    'auth.confirmPass': 'Confirm password',
    'auth.forgotPass': 'Forgot password?',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.orContinue': 'or continue with',
    'auth.terms': 'By creating an account you agree to our Terms and Privacy Policy.',
    'portfolio.3d.label': '3D Modeling',
    'portfolio.3d.title': 'Bas Relief, Medals & Coins',
    'portfolio.3d.sub': 'Precision-crafted 3D models for production: numismatic designs, commemorative medals, bas relief panels, and custom souvenirs.',
    'portfolio.ai.label': 'AI Content',
    'portfolio.ai.title': 'Generated Images & Video',
    'portfolio.ai.sub': 'Exploring the frontier of AI-assisted creativity — concept art, stylized renders, and short-form video.',
    'portfolio.filter.all': 'All',
    'portfolio.filter.basRelief': 'Bas Relief',
    'portfolio.filter.medals': 'Medals',
    'portfolio.filter.coins': 'Coins',
    'portfolio.filter.souvenirs': 'Souvenirs',
    'portfolio.filter.images': 'Images',
    'portfolio.filter.video': 'Video',
  },
  ru: {
    'nav.portfolio': 'Портфолио',
    'nav.news': 'Новости',
    'nav.articles': 'Статьи',
    'nav.shop': 'Магазин',
    'nav.forum': 'Форум',
    'nav.contact': 'Контакты',
    'nav.login': 'Войти',
    'hero.label': 'Творческое Портфолио',
    'hero.title1': 'Где Мастерство',
    'hero.title2': 'Встречает',
    'hero.title3': 'Интеллект',
    'hero.sub': '3D барельефы, медали и монеты вместе с AI-изображениями и видео — одна творческая вселенная.',
    'hero.cta1': 'Смотреть Портфолио',
    'hero.cta2': 'Перейти в Магазин',
    'portfolio.label': 'Избранные Работы',
    'portfolio.title': 'Двойная Творческая Практика',
    'portfolio.sub': 'Рукотворные 3D-модели и AI-контент, каждое направление обогащает другое.',
    'portfolio.tab3d': '3D Моделирование',
    'portfolio.tabAI': 'AI Контент',
    'portfolio.viewAll': 'Смотреть всё Портфолио',
    'featured.label': 'Последние Работы',
    'featured.title': 'Новые Творения',
    'news.label': 'Обновления',
    'news.title': 'Новости и Статьи',
    'news.sub': 'Материалы о 3D-моделировании, AI-генерации контента и их взаимодействии.',
    'news.readMore': 'Читать статью',
    'news.viewAll': 'Все Статьи',
    'shop.label': 'Магазин',
    'shop.title': 'Приобрести Работу',
    'shop.sub': 'Цифровые загрузки, файлы 3D-моделей и эксклюзивные принты.',
    'shop.addCart': 'В корзину',
    'shop.viewAll': 'Весь Магазин',
    'forum.label': 'Сообщество',
    'forum.title': 'Присоединиться к Обсуждению',
    'forum.sub': 'Общайтесь с 3D-художниками и AI-энтузиастами. Делитесь работами, получайте отзывы.',
    'forum.join': 'Войти на Форум',
    'contact.label': 'Связаться',
    'contact.title': 'Заказ или Сотрудничество',
    'contact.sub': 'Принимаю заказы на 3D-моделирование, AI-проекты и творческое сотрудничество.',
    'contact.send': 'Отправить Сообщение',
    'contact.name': 'Ваше Имя',
    'contact.email': 'Эл. почта',
    'contact.subject': 'Тема',
    'contact.message': 'Расскажите о вашем проекте...',
    'footer.tagline': 'Где 3D-мастерство встречает AI-интеллект.',
    'auth.signIn': 'Войти',
    'auth.signUp': 'Создать Аккаунт',
    'auth.email': 'Эл. адрес',
    'auth.password': 'Пароль',
    'auth.name': 'Полное имя',
    'auth.confirmPass': 'Подтвердите пароль',
    'auth.forgotPass': 'Забыли пароль?',
    'auth.noAccount': 'Нет аккаунта?',
    'auth.hasAccount': 'Уже есть аккаунт?',
    'auth.orContinue': 'или продолжить через',
    'auth.terms': 'Создавая аккаунт, вы принимаете Условия использования и Политику конфиденциальности.',
    'portfolio.3d.label': '3D Моделирование',
    'portfolio.3d.title': 'Барельефы, Медали и Монеты',
    'portfolio.3d.sub': 'Точные 3D-модели для производства: нумизматические дизайны, памятные медали, барельефные панели и сувениры.',
    'portfolio.ai.label': 'AI Контент',
    'portfolio.ai.title': 'Сгенерированные Изображения и Видео',
    'portfolio.ai.sub': 'Исследование возможностей AI-творчества — концепт-арт, стилизованные рендеры и короткометражное видео.',
    'portfolio.filter.all': 'Все',
    'portfolio.filter.basRelief': 'Барельефы',
    'portfolio.filter.medals': 'Медали',
    'portfolio.filter.coins': 'Монеты',
    'portfolio.filter.souvenirs': 'Сувениры',
    'portfolio.filter.images': 'Изображения',
    'portfolio.filter.video': 'Видео',
  },
};

const LangContext = createContext<LangContextType>({
  lang: 'en',
  setLang: () => {},
  t: (k) => k,
});

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('en');
  const t = (key: string) => translations[lang][key] ?? key;
  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}